### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by mzedeler** [grantcarthew/node-scalable-blob-store#7]
I am using sbs for a http enabled blob store, and from version 3.0.9 to version 4.0.0 I have experienced a significant performance degradation. When I test creating 1000 small files with version 3.0.9, my code (including sbs) takes 12 seconds. With version 4.0.0, it takes 20 seconds, so somehow sbs is responsible for a 66% increase in total run time (which means that sbs by itself probably has an even worse performance degradation from 3.0.9 to 4.0.0).

Is there any ongoing work to improve performance and is there any knowledge about what the source of the degradation could be?

**Comment by grantcarthew** [comment]
Hi @mzedeler,

If you read the [warning](https://github.com/grantcarthew/node-scalable-blob-store#warning) at the top of the README page you will see that this is a known issue. I haven't looked at scalable-blob-store for a while. I plan on using it for a few projects so it will get some love at some point.

Unless you want to dig in now and work on it, roll back to v3.0.9.

I'll keep this issue open until I have fixed it.

Thanks.

**Comment by grantcarthew** [comment]
Closing this now due to no more experimental APIs in use.
